/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan1;

/**
 *
 * @author princexod
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proses = new javax.swing.JButton();
        editNama = new javax.swing.JTextField();
        editKelas = new javax.swing.JTextField();
        editAlamat = new javax.swing.JTextField();
        hasilNama = new javax.swing.JTextField();
        hasilKelas = new javax.swing.JTextField();
        hasilAlamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(130, 160, 130, 30);

        editNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNamaActionPerformed(evt);
            }
        });
        getContentPane().add(editNama);
        editNama.setBounds(130, 40, 130, 30);

        editKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editKelasActionPerformed(evt);
            }
        });
        getContentPane().add(editKelas);
        editKelas.setBounds(130, 80, 130, 30);
        getContentPane().add(editAlamat);
        editAlamat.setBounds(130, 120, 130, 30);

        hasilNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilNamaActionPerformed(evt);
            }
        });
        getContentPane().add(hasilNama);
        hasilNama.setBounds(130, 200, 130, 30);
        getContentPane().add(hasilKelas);
        hasilKelas.setBounds(130, 240, 130, 30);

        hasilAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(hasilAlamat);
        hasilAlamat.setBounds(130, 280, 130, 30);

        jLabel1.setText("Formulir");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 10, 70, 20);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 40, 40, 14);

        jLabel3.setText("Kelas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 80, 40, 14);

        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 120, 40, 14);

        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 210, 40, 20);

        jLabel6.setText("Kelas");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 250, 40, 14);

        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 280, 40, 14);

        setBounds(0, 0, 368, 361);
    }// </editor-fold>//GEN-END:initComponents

    private void editNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNamaActionPerformed

    private void hasilAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilAlamatActionPerformed

    private void editKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editKelasActionPerformed

    private void hasilNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilNamaActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        String nama = editNama.getText();
        hasilNama.setText(nama);
        String kelas = editKelas.getText();
        hasilKelas.setText(kelas);
        String alamat = editAlamat.getText();
        hasilAlamat.setText(alamat);
        
    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editAlamat;
    private javax.swing.JTextField editKelas;
    private javax.swing.JTextField editNama;
    private javax.swing.JTextField hasilAlamat;
    private javax.swing.JTextField hasilKelas;
    private javax.swing.JTextField hasilNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
